purcell/emacs.d

lisp/init-common-lisp.el
Clozure Common Lisp (ccl) is one of the most used lisp compilers around, as much as sbcl. It's probably nice to have it loaded as the others already listed.
=> Added ccl to the slime-lisp-implementations

lisp/init-org.el
The original url has become invalid.
=> update url for ditaa

lisp/init-exec-path.el
Default set the $PATH variable in X window systems.
=> $PATH for X window

lisp/init-clojure-cider.el
`cider-turn-on-eldoc-mode` was removed from Cider in version 9, which was released June 2015. [Changelog](https://github.com/clojure-emacs/cider/blob/master/CHANGELOG.md#changes-6)
The substitution is just to use `'eldoc-mode` now.
=> Replace removed Cider hook

lisp/.dir-locals.el
Your `~/.emacs.d/lisp/.dir-locals.el` seems to be written manually, the result is that every time I want to edit your files, will pop up "unsafe" prompt box.
If you are deliberately doing so, Please forgive my rudeness.
Thank you.
=> Make Directory Local Variables conform to standard specifications

lisp/init-ivy.el
Hello:
I think putting the code within `after-load` does not really make sure that ivy-mode is enabled.
A practical example:
If I removed `~/.emacs.d/` and re-download your configuration, `ivy-switch-buffer` will not be enabled after the first startup. 
And no key binding, unless `counsel-M-x`, `counsel-find-file`.
I must manually enable `ivy-switch-buffer` with` M-x ivy-switch-buffer`
This is an example image:
after <kbd>C-x b</kbd>
This is an example image of improved:
after<kbd>C-x b</kbd>
Sorry for my poor English.
=> Improved "Make sure ivy-mode is enabled"

lisp/init-editing-utils.el
Hey Steve! Hope all is well with you.
Thought you might like to merge this into your config, it's a tiny change that resolves a keybinding clash between `dash-at-point` and `md/duplicate-up`.
I chose to change the keybinding for `md/duplicate-up` to `C-c u` and leave `dash-at-point` as `C-c D` because that's what I'm used to 😛 .
Cheers,
Kieran
=> Resolve global keymap clash between dash-at-point & md/duplicate-up

lisp/init-darcs.el
Hello:
The author of vc-darcs seems to have fixed this bug.
In short, after I remove the code to fix it, I did not see anything wrong with that variable.
=> Remove defunct config for vc-darcs

lisp/init-org.el
In `org-20171225`, `org-remove-empty-drawer-at` only accepts one argument `POS`. And, there is `org-clock-remove-empty-clock-drawer` in `org-clock-out-hook` by default.
=> Remove sanityinc/remove-empty-drawer-on-clock-out because it is broken and not needed in org-20171225

.travis.yml
The Emacs Version Manager (EVM) now includes Emacs 26.1.
=> Test against Emacs 26.1

lisp/init-projectile.el
Hello：
See https://github.com/bbatsov/projectile/blob/9c6e9813abec6e067c659e9107bf356086a95e04/projectile.el#L156 
and https://github.com/bbatsov/projectile/commit/9c6e9813abec6e067c659e9107bf356086a95e04
This variable is also obsolete as projectile removes the default shortcuts.
This  change has another advantage... If the users use `which-key`, they will see the correct `projectile-command-map` instead of `prefix`. But `guide-key` doesn't have this problem, so it doesn't seem to be an advantage...
Thanks.
=> Use define-key instead of outdated projectile-keymap-prefix

lisp/init-javascript.el
Hello:
This PR contains two changes:
+ Drop js2-basic-offset setting
Because it is an alias for js-indent-level
https://github.com/mooz/js2-mode/blob/2ed3cc070c7819556c9c89826b0f5c4629b104ef/js2-mode.el#L102
+ Remove duplicate code
You seem to have an `(after-load 'js2-mode)` nested inside `(after-load 'js2-mode)`.
Thanks.
=> Improve javascript configuration

init.el
Hello
This change can slightly reduce the initialization time. And I think adjusting `gc-cons-threshold` should be something to do after startup.
Thanks.
=> Set gc-cons-threshold to normal-gc-cons-threshold in emacs-startup-hook

lisp/init-org.el
Hello
You are already set up `org-archive-mark-down` in [init-org.el#Line 323](https://github.com/purcell/emacs.d/blob/a3d5c76d8406e93892617a774e821376d80e45c7/lisp/init-org.el#L323).
Thanks.
=> Remove duplicate org-archive-mark-done setting

lisp/init-org.el
Hello:
It seems that value of `blink-cursor-interval` does not back to the original value after disable prose-mode.
Thanks.
=> Kill all local variables when disable prose-mode

lisp/init-lisp.el
Hello:
This configuration seems to no longer use indent-guide.
Thanks.
BTW: I recently found that there is not very good indent-guide plugin in Emacs.
Another point to ask is... **Why is the name of the hook lispy**?
=> Remove defunct sanityinc/disable-indent-guide

lisp/init-elm.el
Hello:
Because`elm-test` is moved to `elm-test-runner`. See https://github.com/juanedi/elm-test-el/blob/master/README.md
Now in MELPA (at least in the mirror of [emacs-china](https://elpa.emacs-china.org)) you can't find `elm-test` anymore.
Thanks.
=> Use elm-test-runner instead of elm-test

lisp/init-projectile.el
Hello
See bbatsov/projectile#1288
Putting this setting in `after-load` will cause the non-file buffers and remote buffers to not display the set modeline lighter correctly.
=> Set shorter projectile modeline correctly

lisp/init-projectile.el
See https://github.com/bbatsov/projectile/commit/19943eb85ff4cb30466568b0d357c22d398e8cf8
`projectile-mode-line-lighter` is obsolete (that is, it is defined as an obsolete variable in the latest version), and continued use will cause problem mentioned in #621 (That is, `" Projectile"` will be displayed in non-file buffers and remote buffers instead of `" Proj"`).
I have been paying attention to the mode-line changes of `projectile` recently. Because this is caused by my issue.
If the inconvenience to you, I'm sorry.
BTW, why do you use so many `setq-default` instead of `setq`?
Thanks.
=> Use projectile-mode-line-prefix to set projectile mode line

.gitignore
Hello:
This configuration doesn't use `auto-complete` and `anything` now.
BTW: I found that your .gitignore should indeed clean up... For example, /swank will not be generated in your current configuration.
Thanks.
=> No longer ignore files that don't exist

lisp/init-lisp.el
Hello:
`my/try-complete-lisp-symbol-without-namespace` has been removed.
Thanks.
=> Remove non-existing hippie-expand item for elisp

lisp/init-html.el
Hello:
I found that `sanityinc/swiper-at-point` (<kbd>M-s /</kbd>) can't be used when writing HTML...
Thanks.
=> Unset key "M-s" for tagedit to avoid conflicting with Emacs default bindings

lisp/init-compile.el
Hello:
I found that under your latest code, the following error message will be generated after compilation:
```
(wrong-number-of-arguments (lambda nil "Save the compilation buffer to find it later." (setq sanityinc/last-compilation-buffer next-error-last-buffer)) 3)
...
```
Thanks.
=> Fix wrong number of arguments for sanityinc/save-compilation-buffer

lisp/init-editing-utils.el
Hello
See https://github.com/purcell/emacs.d/commit/71045816d420b345bc74de1d8467e1179b8c0fa8
So there is no need to quote css-mode-hook separately here.
Thanks.
=> Drop more unnecessary css-mode-hook references

lisp/init-ivy.el
Hello:
I found the ivy-initial-input for `man` is wrong, so make this change.
Thanks.
=> Update ivy-initial-inputs-alist settings

lisp/init-javascript.el
Hello:
I found that `js-comint` has updated a lot of things, but its documentation has not been updated.
Fixes #651
=> Fix js comint

lisp/init-sessions.el
Hello:
I don't know what was append here, but it's gone now.
So I deleted the "append" here and changed it to a list.
Thanks
=> Drop unnecessary "append" in desktop-globals-to-save setting

lisp/init-ruby.el
Hello:
There is only a built-in `ruby-mode`. And it is a derived mode of `prog-mode`.
Thanks.
=> Remove defunct workaround for ruby-mode

lisp/init-ruby.el
Hello:
This change improves `init-ruby.el`:
**Remove unnecessary let bindings** :
These two let bindings seem unnecessary.
`m` seems to be because there was a lot of code here, but now there are only two lines left.
And for `html-erb-modes`, I don't know what it is for. But I don't think that using a direct list will reduce readability.
**Use comments beginning with two semicolons**:
Comments beginning with a single semicolon always cause formatting confusion.
Please forgive me for obsessive-compulsive disorder and poor English.
Thanks.
=> Improve init-ruby.el

.gitignore
I think we don't need `.cache/` directory in repo. It will be generated automatically.
=>  Add `.cache/` to .gitignore file.

lisp/init-paredit.el
Hello 
See https://mumble.net/~campbell/emacs/paredit.el
```elisp
...
;;;###autoload
(defun enable-paredit-mode ()
"Turn on pseudo-structural editing of Lisp code."
(interactive)
(paredit-mode +1))
...
```
Thank you.
=> No longer autoload "enable-paredit-mode" manually

lisp/init-git.el
Hello:
Since magit switched to `transient`, `magit-dispath-popup` has been removed and it has no "obsolete function alias".
Thanks.
=> Bind magit-dispatch instead of magit-dispatch-popup to "C-x M-g"

lisp/init-locales.el
Hello:
`(prefer-coding-system)` can handle these. So those removed are superfluous.
Thanks.
=> Remove redundant coding system configuration

lisp/init-javascript.el
Attempting to load coffee-mode causes the error
`File mode specification error: (void-variable js2-mode)`.
If js2-mode was already enabled in the buffer, the error is instead
`Symbol's value as variable is void: js2-mode`
This problem is resolved by quoting `js2-mode`.
=> Fix js2-mode error when loading coffee-mode on emacs 25.2

lisp/init-python.el
Currently, it complains that "No Path provided. Nothing to do 😴". Apparently black doesn't read from stdin even if no file path is provided.
=> Add "-" arg to make black reformatter read from stdin

lisp/init-minibuffer.el
The consult-customize function will now report a message when using (kbd ...) as a value for the :preview-key.
See https://github.com/doomemacs/doomemacs/issues/7064.
=> [minibuffer] Fix "Invalid preview key" message in minibuffer
